substitutions:
  name_esp32c3: ""
  friendly_name: ""
  api_key: ""

esphome:
  name: ${name_esp32c3}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

api:
  encryption:
    key: ${api_key}

logger: